"""The rule store — persistent, cross-project memory for authored rules.

A rules file lives in one repo and is forgotten the moment you work somewhere
else. The store is the layer above that: rules you have written once, kept in
one place, grouped into named **bundles** you can stack (a `base` bundle plus a
per-project overlay), and composed back out into an ordinary rules file that any
agent auto-loads.

Design constraints, deliberately the same ones the rest of mutalyze lives under:

- **Deterministic and offline.** No LLM, no network. Importing a rules file
  reuses Phase 1's own extractor (:func:`extract_candidates`), so what lands in
  the store is exactly what the compiler would have seen.
- **Nothing is decided for the user.** Duplicates and conflicts are *flagged*,
  never auto-resolved, and never silently dropped. Composing writes to stdout
  unless an output path is given explicitly.
- **Local only.** The store is a file on this machine. Nothing is transmitted.

This module returns data; it never writes to stdout. The CLI does the printing.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from datetime import date
from typing import Dict, List, Optional, Set, Tuple

import yaml

from .compile_rules import (
    _BACKTICK_RE,
    _NEG_RE,
    classify,
    extract_candidates,
    find_rules_files,
)

STORE_ENV = "MUTALYZE_STORE"
DEFAULT_BUNDLE = "base"
GENERATED_MARKER = "<!-- generated by mutalyze rules compose -->"


def store_path() -> str:
    """Where the store lives. Overridable for tests and for keeping a store
    alongside a repo instead of in the home directory."""
    override = os.environ.get(STORE_ENV)
    if override:
        return os.path.abspath(os.path.expanduser(override))
    return os.path.expanduser(os.path.join("~", ".mutalyze", "rules.yaml"))


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class StoredRule:
    id: str
    text: str
    bundle: str = DEFAULT_BUNDLE
    source: str = ""
    added: str = ""
    status: str = "active"  # active | disabled

    def to_obj(self) -> Dict[str, str]:
        out = {"id": self.id, "text": self.text, "bundle": self.bundle}
        if self.source:
            out["source"] = self.source
        if self.added:
            out["added"] = self.added
        if self.status != "active":
            out["status"] = self.status
        return out


@dataclass
class Store:
    path: str
    rules: List[StoredRule] = field(default_factory=list)
    next_id: int = 1
    version: int = 1

    # -- lookups ------------------------------------------------------------
    def active(self) -> List[StoredRule]:
        return [r for r in self.rules if r.status == "active"]

    def bundles(self) -> List[str]:
        seen: List[str] = []
        for r in self.rules:
            if r.bundle not in seen:
                seen.append(r.bundle)
        return seen

    def in_bundle(self, bundle: str) -> List[StoredRule]:
        return [r for r in self.rules if r.bundle == bundle]

    def find(self, ident: str) -> Optional[StoredRule]:
        """Exact id, case-insensitive, or an unambiguous prefix."""
        want = ident.strip().upper()
        for r in self.rules:
            if r.id.upper() == want:
                return r
        matches = [r for r in self.rules if r.id.upper().startswith(want)]
        return matches[0] if len(matches) == 1 else None

    def to_yaml(self) -> str:
        doc = {
            "version": self.version,
            "next_id": self.next_id,
            "rules": [r.to_obj() for r in self.rules],
        }
        header = (
            "# mutalyze rule store — your rules, kept across projects.\n"
            "# Hand-editable: fix wording, change a bundle, or delete a rule.\n"
            "# `mutalyze rules compose` turns bundles back into a rules file.\n"
        )
        return header + yaml.safe_dump(doc, sort_keys=False, width=100, allow_unicode=True)


def load_store(path: Optional[str] = None) -> Store:
    p = path or store_path()
    if not os.path.exists(p):
        return Store(path=p)
    with open(p, "r", encoding="utf-8") as fh:
        doc = yaml.safe_load(fh) or {}
    rules: List[StoredRule] = []
    for raw in doc.get("rules") or []:
        if not isinstance(raw, dict) or not str(raw.get("text", "")).strip():
            continue
        rules.append(
            StoredRule(
                id=str(raw.get("id", "")),
                text=str(raw.get("text", "")),
                bundle=str(raw.get("bundle", DEFAULT_BUNDLE) or DEFAULT_BUNDLE),
                source=str(raw.get("source", "") or ""),
                added=str(raw.get("added", "") or ""),
                status=str(raw.get("status", "active") or "active"),
            )
        )
    return Store(
        path=p,
        rules=rules,
        next_id=int(doc.get("next_id", len(rules) + 1) or len(rules) + 1),
        version=int(doc.get("version", 1) or 1),
    )


def save_store(store: Store) -> None:
    parent = os.path.dirname(store.path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(store.path, "w", encoding="utf-8") as fh:
        fh.write(store.to_yaml())


# ---------------------------------------------------------------------------
# Normalization / dedupe
# ---------------------------------------------------------------------------

def norm_key(text: str) -> str:
    """Same normalization Phase 1 uses to dedupe rules, plus trailing
    punctuation, so "Use `rg`." and "use  `rg`" collapse to one key."""
    return re.sub(r"\s+", " ", text.strip().lower()).rstrip(".;,:!")


def add_rule(
    store: Store,
    text: str,
    bundle: str = DEFAULT_BUNDLE,
    source: str = "",
) -> Tuple[Optional[StoredRule], Optional[str]]:
    """Add one rule. Returns (rule, None) or (None, reason) when it is a
    duplicate — importing the same file twice is a no-op, not a pile of copies.
    """
    text = text.strip()
    if not text:
        return (None, "empty rule")
    key = norm_key(text)
    for r in store.rules:
        if norm_key(r.text) == key and r.bundle == bundle:
            return (None, "already in bundle '%s' as %s" % (bundle, r.id))
    rule = StoredRule(
        id="R%03d" % store.next_id,
        text=text,
        bundle=bundle,
        source=source,
        added=date.today().isoformat(),
    )
    store.next_id += 1
    store.rules.append(rule)
    return (rule, None)


def remove_rule(store: Store, ident: str) -> Optional[StoredRule]:
    rule = store.find(ident)
    if rule is None:
        return None
    store.rules = [r for r in store.rules if r is not rule]
    return rule


# ---------------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------------

@dataclass
class ImportResult:
    source: str
    added: List[StoredRule] = field(default_factory=list)
    skipped: List[Tuple[str, str]] = field(default_factory=list)  # (text, reason)


def import_rules_file(
    store: Store,
    target: str,
    bundle: str = DEFAULT_BUNDLE,
) -> Tuple[Optional[ImportResult], Optional[str]]:
    """Import normative lines from a rules file, or from a repo containing one.

    Uses Phase 1's extractor, so the store holds the same lines the compiler
    would act on — not a second, divergent idea of what a rule is.
    """
    target = os.path.abspath(os.path.expanduser(target))
    if os.path.isdir(target):
        files = find_rules_files(target)
        if not files:
            return (None, "no CLAUDE.md or AGENTS.md found in %s" % target)
        path = files[0]
    elif os.path.exists(target):
        path = target
    else:
        return (None, "no such file or directory: %s" % target)

    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        text = fh.read()

    result = ImportResult(source=path)
    candidates = extract_candidates(text)
    if not candidates:
        return (result, None)
    for line in candidates:
        rule, reason = add_rule(store, line, bundle=bundle, source=path)
        if rule is not None:
            result.added.append(rule)
        else:
            result.skipped.append((line, reason or "skipped"))
    return (result, None)


# ---------------------------------------------------------------------------
# Checkability (reuses the Phase 1 classifier — no second implementation)
# ---------------------------------------------------------------------------

def checkability(text: str) -> Tuple[bool, str]:
    """(True, check-type) if mutalyze could mechanically verify this rule,
    else (False, reason). Purely informational: an unsupported rule is still a
    perfectly good rule for an agent to read, it just can't be audited."""
    check, reason = classify(text)
    if check is not None:
        return (True, check.type)
    return (False, reason or "not mechanically verifiable")


# ---------------------------------------------------------------------------
# Conflict detection — flag, never resolve
# ---------------------------------------------------------------------------

_REJECT_RE = re.compile(
    r"(?:not|instead of|rather than|don't use|never use|avoid|over)\s+`([^`]+)`",
    re.IGNORECASE,
)
_ENDORSE_RE = re.compile(r"(?:use|prefer|run|switch to)\s+`([^`]+)`", re.IGNORECASE)


def rule_tokens(text: str) -> Tuple[Set[str], Set[str]]:
    """Split a rule's backticked tokens into (forbidden, endorsed).

    "Use `rg` (not `grep`)" endorses rg and forbids grep — treating both as
    "mentioned" would make every prefer-rule look like it conflicts with
    itself, so the sanctioned and rejected sides are kept apart.
    """
    forbidden: Set[str] = set()
    endorsed: Set[str] = set()
    spans = [s.strip() for s in _BACKTICK_RE.findall(text) if s.strip()]

    rejected = {m.strip().lower() for m in _REJECT_RE.findall(text)}
    approved = {m.strip().lower() for m in _ENDORSE_RE.findall(text)}
    forbidden |= rejected
    endorsed |= approved - rejected

    if not rejected and _NEG_RE.search(text):
        # A plain prohibition ("never use `eval(`"): every token is forbidden.
        forbidden |= {s.lower() for s in spans} - approved
    return (forbidden, endorsed)


@dataclass
class Conflict:
    a: StoredRule
    b: StoredRule
    token: str

    def describe(self) -> str:
        return "`%s`: %s endorses it, %s forbids it" % (self.token, self.a.id, self.b.id)


def find_conflicts(rules: List[StoredRule]) -> List[Conflict]:
    """Rules that pull in opposite directions on the same token.

    Conservative on purpose: only an explicit endorse-vs-forbid on the *same*
    token counts. Anything softer is a judgement call, and this module does not
    make judgement calls.
    """
    parsed = [(r, rule_tokens(r.text)) for r in rules]
    out: List[Conflict] = []
    for i, (ra, (fa, ea)) in enumerate(parsed):
        for rb, (fb, eb) in parsed[i + 1:]:
            for token in sorted(ea & fb):  # a endorses what b forbids
                out.append(Conflict(a=ra, b=rb, token=token))
            for token in sorted(eb & fa):  # b endorses what a forbids
                out.append(Conflict(a=rb, b=ra, token=token))
    return out


def find_duplicates(rules: List[StoredRule]) -> List[Tuple[StoredRule, StoredRule]]:
    """Same rule text present twice (across bundles, typically)."""
    seen: Dict[str, StoredRule] = {}
    out: List[Tuple[StoredRule, StoredRule]] = []
    for r in rules:
        key = norm_key(r.text)
        if key in seen:
            out.append((seen[key], r))
        else:
            seen[key] = r
    return out


# ---------------------------------------------------------------------------
# Compose — bundles back into an ordinary rules file
# ---------------------------------------------------------------------------

@dataclass
class ComposeResult:
    text: str
    used: List[StoredRule] = field(default_factory=list)
    duplicates: List[Tuple[StoredRule, StoredRule]] = field(default_factory=list)
    conflicts: List[Conflict] = field(default_factory=list)
    bundles: List[str] = field(default_factory=list)


def compose(
    store: Store,
    bundles: Optional[List[str]] = None,
    title: str = "Project rules",
) -> ComposeResult:
    """Stack bundles in the order given into one rules file.

    Earlier bundles win a duplicate; the loser is reported, not hidden. Output
    is Markdown bullets under per-bundle headings, which is exactly the shape
    Phase 1's extractor reads back — so a composed file can be audited by
    `mutalyze check` without any special handling.
    """
    names = bundles or store.bundles() or [DEFAULT_BUNDLE]
    result = ComposeResult(text="", bundles=list(names))

    seen: Dict[str, StoredRule] = {}
    ordered: List[Tuple[str, List[StoredRule]]] = []
    for name in names:
        kept: List[StoredRule] = []
        for rule in store.in_bundle(name):
            if rule.status != "active":
                continue
            key = norm_key(rule.text)
            if key in seen:
                result.duplicates.append((seen[key], rule))
                continue
            seen[key] = rule
            kept.append(rule)
            result.used.append(rule)
        ordered.append((name, kept))

    result.conflicts = find_conflicts(result.used)

    lines: List[str] = ["# %s" % title, "", GENERATED_MARKER]
    lines.append("<!-- bundles: %s · %d rules · edit the store, not this file -->"
                 % (", ".join(names), len(result.used)))
    lines.append("")
    for name, kept in ordered:
        if not kept:
            continue
        lines.append("## %s" % name)
        lines.append("")
        for rule in kept:
            lines.append("- %s" % rule.text)
        lines.append("")
    if result.conflicts:
        lines.append("<!-- mutalyze flagged conflicting rules; resolve in the store:")
        for c in result.conflicts:
            lines.append("     %s" % c.describe())
        lines.append("-->")
        lines.append("")
    result.text = "\n".join(lines).rstrip() + "\n"
    return result


def is_generated(path: str) -> bool:
    """True if this file was written by compose — safe to overwrite."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return GENERATED_MARKER in fh.read(4096)
    except OSError:
        return False
